# Generated by Django 3.0.8 on 2020-10-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnaiul',
            field=models.ImageField(upload_to='main/img'),
        ),
    ]
