# Generated by Django 3.0.8 on 2020-10-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201017_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(upload_to='main/categories'),
        ),
    ]
