# Generated by Django 3.0.8 on 2020-10-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnaiul',
            field=models.ImageField(upload_to='static/img/blogimg'),
        ),
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(upload_to='static/img/category'),
        ),
    ]
