# Generated by Django 3.0.8 on 2020-10-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201017_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnaiul',
            field=models.ImageField(upload_to='main/blogimg'),
        ),
    ]
