# Generated by Django 3.0.8 on 2020-10-18 16:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201018_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text2',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
