# Generated by Django 3.0.8 on 2020-10-19 05:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_post_text2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
