# Generated by Django 3.0.8 on 2020-10-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201021_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='img_url',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
