# Generated by Django 3.0.8 on 2020-10-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='commentDesc',
            new_name='text',
        ),
    ]
